### ISSUE TITLE
Is the method automatically matching the size of the triplanes with the (normalized) coordinates of the scene?

### ISSUE THREAD

**Issue by Mariusmarten** [Giodiro/kplanes_nerfstudio#1]
The original nerfstudio data parser is able to perform some rescaling (and does so as default I think since I have no problem when training with the nerfactor model). When using the Kplanes I have a problem with a mismatch between 'center of triplane coordinates' and 'center of data coordinates' so I am wondering, is the nerfstudio data parser still applied as default?

_image 1:_ when using k-planes model
![mismatch](https://user-images.githubusercontent.com/39059976/236198379-62136c66-d067-4f5b-be8d-98e28c06b1ad.png)

_image 2:_ when using nerfacto model
![match](https://user-images.githubusercontent.com/39059976/236198394-4720c1c8-7b43-4a38-bd74-94f6d6e6525c.png)

**Comment by Giodiro** [comment]
Hi @Mariusmarten
This is interesting, as there is no dataparsing code in this repository, so I would have not expected any difference.

One thing that comes to mind is that different methods may have different dataparsing defaults. Could you paste the **full configuration** (as output when running from CLI) for both runs? Maybe we can spot the error from there.

**Comment by Mariusmarten** [comment]
Hi @Giodiro, I am not sure why the standard dataparser was not applied as a default but if I pass the NeRFStudio dataparser argument explicitly it worked so I will close this issue. Thank you for the implementation btw!
