### ISSUE TITLE
Dynerf dataloader support

### ISSUE THREAD

**Issue by Friedrich-M** [Giodiro/kplanes_nerfstudio#15]
Thanks a lot for your great work. 

I noticed that the kplanes_nerfstudio repo only supports training on the D-NeRF dataset, and I wonder how can I train the Kplanes on the DyNeRF dataset based on Nerfstudio framework.

Appreciate your work on getting this accessible.

**Comment by Giodiro** [comment]
Hi @Friedrich-M , 
unfortunately dataset support comes from the main nerfstudio repository (we only implement the model here), so you could try to open an issue there to see if they are interested in adding a DyNeRF data manager.

Alternatively you can try the [official repository for k-planes](https://github.com/sarafridov/K-Planes) where we have a dynerf data loader (but no nerfstudio support).

**Comment by Friedrich-M** [comment]
Thanks a lot! I will try it.
