### ISSUE TITLE
Hyperparameter settings for loss

### ISSUE THREAD

**Issue by Friedrich-M** [Giodiro/kplanes_nerfstudio#17]
Thanks for your great work! However, I noticed that the parameter settings for loss in your repo are different from those in the original Kplanes repo. Thus, I'm curious to understand whether this modification reflects an experimentally validated improvement or if there are specific reasons behind this adjustment. Your insights would be greatly appreciated.

**Comment by Giodiro** [comment]
Hi @Friedrich-M 
The losses in the original repo had a few small bugs, mostly related to weird choices of normalization.
They're fixed in this code but the hyperparameters needed retuning.

**Comment by Friedrich-M** [comment]
Thanks a lot for your answer! That's really helpful.
