### ISSUE TITLE
Does not work

### ISSUE THREAD

**Issue by catid** [Giodiro/kplanes_nerfstudio#2]
Followed instructions got this error:

FileNotFoundError: [Errno 2] No such file or directory: 'data/nerfstudio/poster/transforms_train.json'

**Comment by catid** [comment]
Manually edited the transforms.json file to transforms_train.json, and then it failed to find the images as well..

**Comment by catid** [comment]
Seems to only train on the blender set.  But also fails on the blender set: https://www.youtube.com/watch?v=VDFlAR1uPyo

**Comment by bvarjavand** [comment]
I have the same issue. I am missing specific keys for 'time' when I try to use kplanes dynamic

**Comment by Giodiro** [comment]
Hi!
I'm rerunning the experiments now to see if something changed wrt when the code was written about a month ago.
It would be useful for debugging if you could be more precise as to what you ran, and what the (command line) output was.
Will update this thread if my runs fail or not.

**Comment by Giodiro** [comment]
Ok I agree it's not working properly, sorry for the late action here.
I'll debug in the morning!

**Comment by bvarjavand** [comment]
Thank you! :)

**Comment by seva1232** [comment]
Hi! Thank you for the awesome work! 
Are there any updates here? The model launches for me, but on a poster dataset it produces something too far from the poster=)

**Comment by Giodiro** [comment]
I think there's a problem with the input coordinates being out of the expected range. Not sure exactly what's happening. On dnerf setting time regularizers to 0 improves numbers a bit but still far from what they should be.
I unfortunately won't have much time to look at this for a few days at least, sorry :(

**Comment by catid** [comment]
NBD

**Comment by Giodiro** [comment]
Hi! Thanks to @wzy-99 who found the missing interlevel loss (to train the proposal nets) this should be fixed! Feel free to reopen if you have other problems :)
