### ISSUE TITLE
Can you please share the training config on nerfstudio?

### ISSUE THREAD

**Issue by coolbeam** [Giodiro/kplanes_nerfstudio#5]
Hi, I'm using the nerfstudio version of kplanes.
I first download data by:
```
ns-download-data dnerf --save-dir ./dnerf_Data
```
Then, I begin to train the model:
```
ns-train kplanes --data ./dnerf_Data/dnerf/lego --output-dir ./output/kplanes-dynamic/D-NeRF/lego
ns-train kplanes-dynamic --data ./dnerf_Data/dnerf/lego --output-dir ./output/kplanes-dynamic/D-NeRF/lego
```
But the training result is not so good. 
I wonder if the default config parameters is not so good and can you please share the training config parameters for reproducing the results?
Below is the kplanes-dynamic results:
![image](https://github.com/Giodiro/kplanes_nerfstudio/assets/50230032/7a6fbf11-9870-45b3-89ed-a7c65f5caed6)

**Comment by Giodiro** [comment]
Hi! There was a bug which prevented correct convergence. Should be fixed now (on the master branch, I'll push to pypi soon)! Feel free to reopen if it's not solved for you.

**Comment by coolbeam** [comment]
Thank you for your kindly help. The bug is fixed, and the results looks good during early training. However, as the training process progresses, the results of the training are slowly getting worse. I'm training using the default parameters. So, is there anything I can do to improve this or is there still a bug in the code? 
![image](https://github.com/Giodiro/kplanes_nerfstudio/assets/50230032/34f4f3b5-fe0e-4ce0-b3d7-5433934b1c9a)
